# Generated by Django 2.1.2 on 2018-10-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
